apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-nextjs
  labels:
    app: portfolio-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-nextjs
  template:
    metadata:
      labels:
        app: portfolio-nextjs
    spec:
      containers:
      - name: portfolio-nextjs
        image: gcr.io/concepts-demo/portfolio-nextjs:latest
        ports:
        - containerPort: 3000
