apiVersion: v1
kind: Service
metadata:
  name: portfolio-nextjs-service
  namespace: agrocd
  labels:
    app: portfolio-nextjs
spec:
  type: LoadBalancer
  selector:
    app: portfolio-nextjs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
