name: Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan, Apply, and Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "concepts-demo"
          credentials_json: ${{ secrets.NG_SA_KEY_GCLOUD }}

      # Configure Docker to Authenticate with GCR
      - name: Configure Docker to Authenticate with GCR
        run: gcloud auth configure-docker

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t portfolio-nextjs:latest .
          docker tag portfolio-nextjs:latest gcr.io/concepts-demo/portfolio-nextjs:latest
          docker push gcr.io/concepts-demo/portfolio-nextjs:latest
